author           = CloudyProton
depends          = default,fakelib,ia_names
description      = Adds poop, feces piles with area denial effect and defecation. Eat to accelerate your bodily cycle.
name             = pooper
optional_depends =
title            = IA Pooper

