author           = CloudyProton
depends          = beds,default, ia_progeny, ia_util, placeable_buckets
description      = Adds poop, feces piles with area denial effect and defecation. Eat to accelerate your bodily cycle. Now with Ketchup and Nature's Call.
name             = pooper
#optional_depends = composting
optional_depends = pedology
title            = IA Pooper

